export const list = [
  {name: 'Pizza Hut', type: 'Restaurant'},
  {name: 'Dominos', type: 'Restaurant'},
  {name: 'McDonald', type: 'Restaurant'},
  {name: 'Burger King', type: 'Restaurant'},
  {name: 'Barbeque Nation', type: 'Restaurant'},
  {name: 'Kwality Walls', type: 'Restaurant'},
  {name: 'Vaishali Sweets', type: 'Restaurant'},
  {name: 'The Park', type: 'Restaurant'},
  {name: 'The Cakes', type: 'Restaurant'},
  {name: 'Croods Square', type: 'Restaurant'},
  {name: 'Capsicum', type: 'Restaurant'},
  {name: 'Subway', type: 'Restaurant'},
  {name: 'Downtown Pizza', type: 'Restaurant'},
  {name: 'KFC', type: 'Restaurant'},
  {name: 'Starbucks', type: 'Restaurant'},
  {name: 'Cafe Coffee Day', type: 'Restaurant'},
  {name: 'One Bite', type: 'Restaurant'},
  {name: 'Kathi Junction', type: 'Restaurant'},
  {name: '7th Heaven', type: 'Restaurant'},
  {name: 'The Green Chilli', type: 'Restaurant'},
  {name: 'The Flamingo Restaurant', type: 'Restaurant'},
  {name: 'Food Plaza', type: 'Restaurant'},
  {name: 'Food Garden', type: 'Restaurant'},
  {name: 'Not Out Cafe', type: 'Restaurant'},
  {name: 'Biryani Bites', type: 'Restaurant'},
  {name: 'Singh Delight', type: 'Restaurant'},
  {name: 'Paprika Food Court', type: 'Restaurant'},
  {name: 'The London Shakes', type: 'Restaurant'},
  {name: 'Non Veg Adda', type: 'Restaurant'},
  {name: 'Pind Balluchi', type: 'Restaurant'},
  {name: 'Chicago Pizza', type: 'Restaurant'},
  {name: 'The Taste Factory', type: 'Restaurant'},
  {name: 'Tanish Dining and Cafe', type: 'Restaurant'},
  {name: 'Biryani Basket', type: 'Restaurant'},
  {name: 'The Coffee House', type: 'Restaurant'},
  {name: 'American Food Court', type: 'Restaurant'},

  {name: 'Pizza', type: 'Dish'},
  {name: 'Burger', type: 'Dish'},
  {name: 'Vada Pav', type: 'Dish'},
  {name: 'Paneer Kadhai', type: 'Dish'},
  {name: 'Paneer Butter Masala', type: 'Dish'},
  {name: 'Paneer Tikka Masala', type: 'Dish'},
  {name: 'Paneer Kaju Masala', type: 'Dish'},
  {name: 'Paneer Malai Tikka', type: 'Dish'},
  {name: 'Paneer Chilli', type: 'Dish'},
  {name: 'Paneer Handi', type: 'Dish'},
  {name: 'Paneer Palak', type: 'Dish'},
  {name: 'Paneer Shahi', type: 'Dish'},
  {name: 'Paneer Mattar', type: 'Dish'},
  {name: 'Paneer Do Pyaza', type: 'Dish'},
  {name: 'Mushroom Mattar', type: 'Dish'},
  {name: 'Mushroom Paneer', type: 'Dish'},
  {name: 'Mushroom Do Pyaza', type: 'Dish'},
  {name: 'Mushroom Masala', type: 'Dish'},
  {name: 'Malai Kofta', type: 'Dish'},
  {name: 'Mixed Vegetables', type: 'Dish'},
  {name: 'Chicken Butter Masala', type: 'Dish'},
  {name: 'Chicken Tikka Masala', type: 'Dish'},
  {name: 'Chicken Chilli', type: 'Dish'},
  {name: 'Roasted Chicken', type: 'Dish'},
  {name: 'Tandori Chicken', type: 'Dish'},
  {name: 'Punjabi Chicken', type: 'Dish'},
  {name: 'Tandori Chicken', type: 'Dish'},
  {name: 'Kadai Chicken', type: 'Dish'},
  {name: 'Handi Chicken', type: 'Dish'},
  {name: 'Chicken Masala', type: 'Dish'},
  {name: 'Chicken Curry', type: 'Dish'},
  {name: 'Chicken Biryani', type: 'Dish'},
  {name: 'Veg Biryani', type: 'Dish'},
  {name: 'Chicken Chilli Garlic Noodles', type: 'Dish'},
  {name: 'Veg Chilli Garlic Noodles', type: 'Dish'},
  {name: 'Veg Hakka Noodles', type: 'Dish'},
  {name: 'Veg Chowmein', type: 'Dish'},
  {name: 'Veg Roll', type: 'Dish'},
  {name: 'Paneer Roll', type: 'Dish'},
  {name: 'Egg Roll', type: 'Dish'},
  {name: 'Chicken Roll', type: 'Dish'},
];
