export const list = [
  {name: 'Pizza Hut', type: 'Restaurant'},
  {name: 'Dominos', type: 'Restaurant'},
  {name: 'McDonald', type: 'Restaurant'},
  {name: 'Burger King', type: 'Restaurant'},
  {name: 'Barbeque Nation', type: 'Restaurant'},
  {name: 'Pizza', type: 'Dish'},
  {name: 'Burger', type: 'Dish'},
  {name: 'Vada Pav', type: 'Dish'},
  {name: 'Paneer Kadhai', type: 'Dish'},
  {name: 'Paneer Butter Masala', type: 'Dish'},
  {name: 'Paneer Tikka Masala', type: 'Dish'},
  {name: 'Paneer Chilli', type: 'Dish'},
  {name: 'Paneer Do Pyaza', type: 'Dish'},
  {name: 'Chicken Butter Masala', type: 'Dish'},
  {name: 'Chicken Tikka Masala', type: 'Dish'},
  {name: 'Chicken Chilli', type: 'Dish'},
  {name: 'Chicken Fry', type: 'Dish'},
  {name: 'Chicken Biryani', type: 'Dish'},
  {name: 'Veg Biryani', type: 'Dish'},
];
